server:
  port: 8080

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${TOKEN_DURATION}
      refresh-token:
        expiration: ${TOKEN_EXPIRATION}

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration/postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/petrohub
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
debug: true